
- schemaLabel: Parameters
  schemaURL: ShExSchemas/R5Plus/Parameters.shex
  dataLabel: parameters-example
  dataURL: FHIR_RDF_Examples/R5/parameters-example.ttl
  queryMap: "{FOCUS a fhir:Parameters}@<Parameters>"
  status: conformant
  