
- schemaLabel: Requirements
  schemaURL: ShExSchemas/R5Plus/Requirements.shex
  dataLabel: Requirements-example2
  dataURL: FHIR_RDF_Examples/R5/Requirements-example2.ttl
  queryMap: "{FOCUS a fhir:Requirements}@<Requirements>"
  status: conformant
  
- schemaLabel: Requirements
  schemaURL: ShExSchemas/R5Plus/Requirements.shex
  dataLabel: Requirements-example1
  dataURL: FHIR_RDF_Examples/R5/Requirements-example1.ttl
  queryMap: "{FOCUS a fhir:Requirements}@<Requirements>"
  status: conformant
  