openapi: 3.0.2
info:
  version: '1.0'
  title: 'PHQ9 Score Interpreter'
  description: PHQ9 Score Interpreter Knowledge Object
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /99999/CAMH1
    description: PHQ9 Score Interpreter
tags:
  - name: KO Endpoints
    description: PHQ9 Score Interpreter Endpoints
paths:
  /score:
    post:
      parameters:
        - $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/parameters/apiversion'
      tags:
        - KO Endpoints
      description: Send total score and get interpretation
      operationId: score
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericresponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
components:
  schemas:
    input:
      type: object
      example: { "Total_PHQ9_Score": 27, "Answers_Array": [1, 0, 2, 3, 2, 1, 1, 1, 1], "Send_Questionnaire": "no"}
